export const ROUTES = {
  home: "/",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  emailSent: "/email-sent",
  resetPassword: "/reset-password",
  resetPasswordSuccess: "/reset-password/success",
  verifyEmail: "/verify-email",
  emailVerified: "/email-verified",
  onboarding: "/onboarding",
  authCallback: "/auth/callback",
  boards: "/boards",
  board: (id: string) => `/boards/${id}`,
  publicCollection: (username: string, slug: string) => `/u/${username}/${slug}`,
  legacyPublicCollection: (slug: string) => `/c/${slug}`,
  creator: (username: string) => `/u/${username}`,
  tag: (slug: string) => `/tag/${slug}`,
  category: (slug: string) => `/${slug}`,
  search: "/search",
  explore: "/explore",
  profile: "/profile",
  profileCollections: "/profile?tab=yours",
  settings: "/settings",
  setup: "/setup",
} as const;

export { getPublicShareUrl } from "@/lib/app-url";
